name = "json-ex"
version = "0.1.0"
license = "license"
author = "luizpbraga"
maintainer = "portilho.braga@gmail.com"
copyright = "Copyright 2022, luizpbraga"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true
[dependencies]
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran" }
