name = "aula27"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "portilho.braga@gmail.com"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
