

name = "aula22"
version = "0.1.0"
license = "NAN"
author = "Oscar Alho"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
